// using-ng-element/angular/src/app/app.component.ts
import {Component} from '@angular/core';

@Component({
    selector: 'app-root',
    template: `

        <p>{{ message }}</p>
        <ng-element
                [attr.increment]="increment"
                [time]="time"
                (doAdd)="handleAddEvent($event)"
        ></ng-element>

    `,
    styles: []
})
export class AppComponent {
    message = 'Hello Angular!';
    increment = 2;
    time = new Date();

    handleAddEvent(e: CustomEvent) {
        console.log(e);
        if (e.detail % 10 === 0) {
            this.message = this.message.split('').reverse().join('');
            this.time = new Date()
        }
    }
}

// using-ng-element/vue/src/App.vue
<template>
    <div id="app">
        <p>{{ message }}</p>
        <ng-element id="nge"
                    v-bind:increment="increment"
                    @doAdd="reverseMessage">
        </ng-element>
    </div>
</template>

<script>

    export default {
        name: 'app',
        data() {
            return {
                message: 'Hello Vue!',
                increment: 2,
                time: new Date()
            }
        },
        methods: {
            reverseMessage: function (e) {
                // eslint-disable-next-line log
                console.log(e);
                if (e.detail % 10 === 0) {
                    this.message = this.message.split('').reverse().join('');
                    this.customElement.time = new Date();
                }
            }
        },
        mounted() {
            this.customElement = document.getElementById('nge');
        }
    }

</script>
